title: Programmering i Python
description: En introduktion till att arbeta med programmeringsspråket Python
theme: just-the-docs

url: https://programmeringipython.se
aux_links: 
  Template Repository: 

color_scheme: dark

callouts:
  warning:
    title: Varning
    color: red

  highlight:
    title: Notera
    color: yellow

logo: "/assets/images/logo2.png"