title: Python Fundamentals
description: En introduktion till att arbeta med programmeringsspråket Python
theme: just-the-docs

url: https://noitaloiv.github.io/pythonFundamentals
aux_links: 
  Template Repository: 

color_scheme: dark
